// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkwEkanW3x1Jl3kolaxyuDM-L9SEvNLwg',
    appId: '1:584480622587:web:2690a8251b71f13d906d5e',
    messagingSenderId: '584480622587',
    projectId: 'news-app-f23dc',
    authDomain: 'news-app-f23dc.firebaseapp.com',
    storageBucket: 'news-app-f23dc.appspot.com',
    measurementId: 'G-YK957V6Y2Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgLbrNiFRgbD2CXaEiVubVwWWtxhaYJEg',
    appId: '1:584480622587:android:fe0ce033d3732c4c906d5e',
    messagingSenderId: '584480622587',
    projectId: 'news-app-f23dc',
    storageBucket: 'news-app-f23dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlCnBg20CcgNFitr11SpMvUPiA6Yr03rM',
    appId: '1:584480622587:ios:f199a1b8bcc1795f906d5e',
    messagingSenderId: '584480622587',
    projectId: 'news-app-f23dc',
    storageBucket: 'news-app-f23dc.appspot.com',
    iosClientId: '584480622587-9nhi09d67uugk22insf9fl2pdaghiv8i.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterBase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlCnBg20CcgNFitr11SpMvUPiA6Yr03rM',
    appId: '1:584480622587:ios:f199a1b8bcc1795f906d5e',
    messagingSenderId: '584480622587',
    projectId: 'news-app-f23dc',
    storageBucket: 'news-app-f23dc.appspot.com',
    iosClientId: '584480622587-9nhi09d67uugk22insf9fl2pdaghiv8i.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterBase',
  );
}
